frr version 10.3
frr defaults traditional
hostname access-wireless-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description CORPORATE_WIFI_VLAN50_CAROL
 ip address 10.10.50.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth2
 description GUEST_WIFI_VLAN40
 ip address 10.10.40.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
!
interface eth3
 description PRIMARY_TO_CORE1
 ip address 10.0.0.9/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth4
 description BACKUP_TO_CORE2
 ip address 10.0.0.13/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
router ospf
 ospf router-id 2.2.2.2
!
