frr version 10.3
frr defaults traditional
hostname security-edge-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description EBGP_TO_ISP1
 ip address 192.0.2.2/30
!
interface eth2
 description TO_CORE1_PRIMARY
 ip address 10.0.0.22/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth3
 description TO_CORE2_SECONDARY
 ip address 10.0.0.26/30
 ip ospf area 0.0.0.0
 ip ospf cost 20
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
ip route 10.0.0.0/8 Null0 250
!
router ospf
 ospf router-id 5.5.5.5
 redistribute bgp metric 20 metric-type 1
!
router bgp 65000
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 timers bgp 3 9
 neighbor 192.0.2.1 remote-as 64501
 network 10.0.0.0/8
!
