frr version 10.3
frr defaults traditional
hostname idc-border-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description TO_CORE1_PRIMARY
 ip address 10.0.1.2/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
interface eth2
 description TO_CORE2_BACKUP
 ip address 10.0.1.6/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
interface eth3
 description TO_IDC_LEAF1
 ip address 10.0.2.1/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
router ospf
 ospf router-id 4.4.4.4
!
