frr version 10.3
frr defaults traditional
hostname campus-core-2
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description TO_WIRED_ACCESS_BACKUP
 ip address 10.0.0.6/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth2
 description TO_WIRELESS_ACCESS_BACKUP
 ip address 10.0.0.14/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth3
 description CORE_PEER_LINK
 ip address 10.0.0.18/30
 ip ospf area 0.0.0.0
 ip ospf cost 5
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth4
 description TO_SECURITY_EDGE1_SECONDARY
 ip address 10.0.0.25/30
 ip ospf area 0.0.0.0
 ip ospf cost 20
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth5
 description TO_SECURITY_EDGE2_PRIMARY
 ip address 10.0.0.33/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth6
 description TO_IDC_LEAF_BACKUP
 ip address 10.0.0.41/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth7
 description TO_DMZ_LEAF_BACKUP
 ip address 10.0.0.49/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
router ospf
 ospf router-id 4.4.4.4
!
