frr version 10.3
frr defaults traditional
hostname dmz-leaf-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description TO_CORE1_PRIMARY
 ip address 10.0.0.46/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth2
 description TO_CORE2_BACKUP
 ip address 10.0.0.50/30
 ip ospf area 0.0.0.0
 ip ospf cost 50
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth3
 description PUBLIC_SERVICE_DMZ_VLAN310
 ip address 10.30.10.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
!
router ospf
 ospf router-id 8.8.8.8
!
