"""
skills/pragmatic/registry.py
──────────────────────────────
Skills backed by real device tools — available in pragmatic mode ONLY.
"""
from __future__ import annotations
from typing import Any

SKILLS: dict[str, dict[str, Any]] = {
    "list_devices": {
        "name":        "List Devices",
        "purpose":     "Enumerate all real network devices in inventory",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["inventory"],
        "description": "Calls list_devices to return live inventory. Filter by type or tag.",
        "parameters":  {"type": "Device type filter", "tag": "Site tag filter"},
        "returns":     "Device table from live inventory",
        "tool_deps":   ["list_devices"],
        "examples":    [{"args": {}, "note": "List all devices"}],
    },
    "get_device_status": {
        "name":        "Device Status",
        "purpose":     "Get live operational status for a device",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["monitoring", "status"],
        "description": "Returns CPU, memory, uptime, and interface summary for one device.",
        "parameters":  {"device_id": "Device identifier"},
        "returns":     "Status dict",
        "tool_deps":   ["get_device_status"],
        "examples":    [],
    },
    "get_device_config": {
        "name":        "Get Device Config",
        "purpose":     "Retrieve running configuration from a real device",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["config", "read"],
        "description": "SSH/NAPALM-backed config retrieval. Can fetch one section.",
        "parameters":  {"device_id": "Device identifier", "section": "Section (optional)"},
        "returns":     "Configuration text",
        "tool_deps":   ["get_device_config"],
        "examples":    [],
    },
    "validate_device_config": {
        "name":        "Validate Device Config",
        "purpose":     "Check device configuration against compliance rules",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["config", "validation"],
        "description": "Fetches config and validates against compliance rule set. Returns issues.",
        "parameters":  {"device_id": "Device identifier"},
        "returns":     "Validation report",
        "tool_deps":   ["validate_device_config"],
        "examples":    [],
    },
    "edit_device_config": {
        "name":        "Edit Device Config",
        "purpose":     "Push a configuration change to a real device",
        "risk_level":  "high",
        "requires_hitl": True,
        "tags":        ["config", "write", "destructive"],
        "description": "Pushes config change via SSH/NAPALM. Always requires HITL approval first.",
        "parameters":  {"device_id": "Device identifier", "section": "Section", "changes": "Change dict", "reason": "Audit reason"},
        "returns":     "Push result with diff",
        "tool_deps":   ["edit_device_config"],
        "examples":    [],
    },
    "get_syslog": {
        "name":        "Get Device Syslog",
        "purpose":     "Retrieve recent syslog entries from a real device",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["logs", "diagnostics"],
        "description": "SSH-backed syslog retrieval. Reports error if device not reachable.",
        "parameters":  {"device_id": "Device identifier", "level": "Severity filter", "lines": "Max lines"},
        "returns":     "Syslog entries",
        "tool_deps":   ["get_syslog"],
        "examples":    [],
    },
    "get_bgp_summary": {
        "name":        "BGP Summary",
        "purpose":     "Get BGP peer state for a router",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["routing", "bgp"],
        "description": "Returns BGP peer table with session state and prefix counts.",
        "parameters":  {"device_id": "Device identifier"},
        "returns":     "BGP peer table",
        "tool_deps":   ["get_bgp_summary"],
        "examples":    [],
    },
    "multi_device_check": {
        "name":        "Multi-Device Check",
        "purpose":     "Run the same diagnostic across multiple real devices",
        "risk_level":  "low",
        "requires_hitl": False,
        "tags":        ["bulk", "diagnostics"],
        "description": "Parallel check across a device list. Returns per-device results table.",
        "parameters":  {"device_ids": "List of device IDs", "check": "status|config|syslog|bgp"},
        "returns":     "Per-device results",
        "tool_deps":   ["multi_device_check"],
        "examples":    [],
    },
}
