frr version 10.3
frr defaults traditional
hostname isp-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description EBGP_TO_ENTERPRISE_EDGE1
 ip address 192.0.2.1/30
!
interface eth2
 description EBGP_TO_ISP2
 ip address 192.0.2.9/30
!
interface eth3
 description SIMULATED_INTERNET_SEGMENT
 ip address 198.51.100.1/24
!
ip route 0.0.0.0/0 Null0 250
!
router bgp 64501
 bgp router-id 9.9.9.9
 no bgp ebgp-requires-policy
 timers bgp 3 9
 neighbor 192.0.2.2 remote-as 65000
 neighbor 192.0.2.10 remote-as 64502
 network 0.0.0.0/0
 network 198.51.100.0/24
!
