frr version 10.3.1_git
frr defaults traditional
hostname branch-r1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description BRANCH_LAN
 ip address 10.10.10.1/24
 ip ospf area 0.0.0.0
 ip ospf passive
exit
!
interface eth2
 description PRIMARY_WAN
 ip address 10.0.0.1/30
 ip ospf area 0.0.0.0
 ip ospf cost 20
 ip ospf dead-interval 4
 ip ospf hello-interval 1
exit
!
interface eth3
 description BACKUP_WAN
 ip address 10.0.0.5/30
 ip ospf area 0.0.0.0
 ip ospf cost 100
 ip ospf dead-interval 4
 ip ospf hello-interval 1
exit
!
router ospf
 ospf router-id 1.1.1.1
exit
!
