frr version 10.3
frr defaults traditional
hostname security-edge-2
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description EBGP_TO_ISP2
 ip address 192.0.2.6/30
!
interface eth2
 description TO_CORE1_SECONDARY
 ip address 10.0.0.30/30
 ip ospf area 0.0.0.0
 ip ospf cost 20
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth3
 description TO_CORE2_PRIMARY
 ip address 10.0.0.34/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
ip route 10.0.0.0/8 Null0 250
!
router ospf
 ospf router-id 6.6.6.6
 redistribute bgp metric 40 metric-type 1
!
router bgp 65000
 bgp router-id 6.6.6.6
 no bgp ebgp-requires-policy
 timers bgp 3 9
 neighbor 192.0.2.5 remote-as 64502
 network 10.0.0.0/8
!
