frr version 10.3
frr defaults traditional
hostname isp-2
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description EBGP_TO_ENTERPRISE_EDGE2
 ip address 192.0.2.5/30
!
interface eth2
 description EBGP_TO_ISP1
 ip address 192.0.2.10/30
!
ip route 0.0.0.0/0 Null0 250
!
router bgp 64502
 bgp router-id 10.10.10.10
 no bgp ebgp-requires-policy
 timers bgp 3 9
 neighbor 192.0.2.6 remote-as 65000
 neighbor 192.0.2.9 remote-as 64501
 network 0.0.0.0/0
!
