frr version 10.3
frr defaults traditional
hostname campus-core-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description TO_WIRED_ACCESS_PRIMARY
 ip address 10.0.0.2/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth2
 description TO_WIRELESS_ACCESS_PRIMARY
 ip address 10.0.0.10/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth3
 description CORE_PEER_LINK
 ip address 10.0.0.17/30
 ip ospf area 0.0.0.0
 ip ospf cost 5
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth4
 description TO_SECURITY_EDGE1_PRIMARY
 ip address 10.0.0.21/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth5
 description TO_SECURITY_EDGE2_SECONDARY
 ip address 10.0.0.29/30
 ip ospf area 0.0.0.0
 ip ospf cost 20
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth6
 description TO_IDC_LEAF_PRIMARY
 ip address 10.0.0.37/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
interface eth7
 description TO_DMZ_LEAF_PRIMARY
 ip address 10.0.0.45/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 3
 ip ospf dead-interval 12
!
router ospf
 ospf router-id 3.3.3.3
!
