frr version 10.3
frr defaults traditional
hostname spine-2
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
 ip ospf area 0.0.0.0
!
interface eth1
 description TO_LEAF_1
 ip address 10.0.0.2/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
interface eth2
 description TO_LEAF_2
 ip address 10.0.0.6/31
 ip ospf area 0.0.0.0
 ip ospf network point-to-point
!
router ospf
 ospf router-id 10.255.0.2
 passive-interface lo
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp default ipv4-unicast
 neighbor EVPN peer-group
 neighbor EVPN remote-as 65000
 neighbor EVPN update-source lo
 neighbor 10.255.1.1 peer-group EVPN
 neighbor 10.255.1.2 peer-group EVPN
 !
 address-family l2vpn evpn
  neighbor EVPN activate
  neighbor EVPN route-reflector-client
 exit-address-family
!
