frr version 10.3
frr defaults traditional
hostname campus-core-1
log stdout informational
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth1
 description TO_ACCESS1
 ip address 10.0.0.2/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
interface eth2
 description TO_IDC_BORDER_PRIMARY
 ip address 10.0.1.1/30
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf hello-interval 1
 ip ospf dead-interval 4
!
router ospf
 ospf router-id 2.2.2.2
!
